[VoiceChatManager]
bEnabled=true
bObtainJoinTokenFromPartyService=false
MaxRetries=0
VoiceChatImplementation=
[EpicPurchaseFlow]
bUsePaymentWeb=false
bEnabled=true
[/Script/FortniteGame.FortGameInstance]
bBattleRoyaleMatchmakingEnabled=true
!FrontEndPlaylistData=ClearArray
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownAlt_Solo, PlaylistAccess=(bEnabled=True, bIsDefaultPlaylist=false, bVisibleWhenDisabled=false, bDisplayAsNew=true, CategoryIndex=0, bDisplayAsLimitedTime=false, DisplayPriority=0))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownAlt_Duos, PlaylistAccess=(bEnabled=True, bIsDefaultPlaylist=false, bVisibleWhenDisabled=false, bDisplayAsNew=true, CategoryIndex=0, bDisplayAsLimitedTime=false, DisplayPriority=1))
+FrontEndPlaylistData=(PlaylistName=Playlist_Showdown_Trios, PlaylistAccess=(bEnabled=True, bIsDefaultPlaylist=false, bVisibleWhenDisabled=false, bDisplayAsNew=true, CategoryIndex=0, bDisplayAsLimitedTime=false, DisplayPriority=2))
+FrontEndPlaylistData=(PlaylistName=Playlist_Showdown_Squads, PlaylistAccess=(bEnabled=True, bIsDefaultPlaylist=false, bVisibleWhenDisabled=false, bDisplayAsNew=true, CategoryIndex=0, bDisplayAsLimitedTime=false, DisplayPriority=3))
+FrontEndPlaylistData=(PlaylistName=Playlist_DefaultSolo, PlaylistAccess=(bEnabled=True, bIsDefaultPlaylist=true, bVisibleWhenDisabled=false, bDisplayAsNew=false, CategoryIndex=0, bDisplayAsLimitedTime=false, DisplayPriority=4))
+FrontEndPlaylistData=(PlaylistName=Playlist_PlaygroundV2, PlaylistAccess=(bEnabled=false, bIsDefaultPlaylist=false, bVisibleWhenDisabled=false, bDisplayAsNew=false, CategoryIndex=2, bDisplayAsLimitedTime=false, DisplayPriority=16))
;+FrontEndPlaylistData=(PlaylistName=Playlist_Campaign, PlaylistAccess=(bEnabled=true, bInvisibleWhenEnabled=true))
[/Script/FortniteGame.FortOnlineAccount]
bEnableEulaCheck=false
bPromptUserAndReverifyAuthToken=false
[/Script/FortniteGame.FortAnalyticsConfig]
UrlEndpoint=
!AltDomains=Clear
b50v50ForceEnabled=true
bPlatoonForceEnabled=true
bShootingTest3Enabled=true
bEvent1ForceEnabled=true
bEvent2ForceEnabled=true
bEvent3ForceEnabled=true
bEvent4ForceEnabled=true
bEvent5ForceEnabled=true
bEvent6ForceEnabled=true
bEvent7ForceEnabled=true
bEvent8ForceEnabled=true
[/Script/Account.OnlineAccountCommon]
bEnableWaitingRoom=false
[/Script/FortniteGame.FortTextHotfixConfig]
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="9F28701D47C7B91B048FEBA378ADDEAE", NativeString="Epic Games", LocalizedStrings=(("en","ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="LoadingScreen", Key="Connecting", NativeString="CONNECTING", LocalizedStrings=(("en","CONNECTING TO ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="FortLoginStatus", Key="LoggingIn", NativeString="Logging In...", LocalizedStrings=(("en","Logging Into ATLAS...")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="OnlineAccount", Key="DoQosPingTests", NativeString="Checking connection to datacenters...", LocalizedStrings=(("en","Checking connection to ATLAS...")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="37020CCD402F073607D9D4A9561EF035", NativeString="PLAY", LocalizedStrings=(("en","Play ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="C8C6606D4ED4B816D4A358A42DFBDD59", NativeString="PLAY", LocalizedStrings=(("en","Play ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="03875FFD49212D2F37B01788C09086B5", NativeString="Quit", LocalizedStrings=(("en","Quit ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="1D20854C403FDD474AE7C8B929815DA2", NativeString="Quit", LocalizedStrings=(("en","Quit ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="1FB7052F40BE8B647B5CA5A362BE8F21", NativeString="Quit", LocalizedStrings=(("en","Quit ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="2E42C9FB4F551A859C05BF99F7E36FB1", NativeString="Quit", LocalizedStrings=(("en","Quit ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="370415344EEEA09D8C01A48F4B8148D7", NativeString="Quit", LocalizedStrings=(("en","Quit ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="538BD1FD46BCEFA4813E2FAFAA07E1A2", NativeString="Quit", LocalizedStrings=(("en","Quit ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="FortOnlineAccount", Key="CreatingParty", NativeString="Creating party...", LocalizedStrings=(("en","Welcome to ATLAS")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="PartyContext", Key="BattleRoyaleInLobby", NativeString="Battle Royale - In Lobby", LocalizedStrings=(("en","ATLAS - Lobby")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="OnlineAccount", Key="TokenExpired", NativeString="Login Expired or Logged In Elsewhere", LocalizedStrings=(("en","Backend Restarted... Restart your game")))
# Victory Royale Text
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="DB13D3C249748AF462C7C4BFBB31ED4A", NativeString="<PlacementNumberSymbol>#</><PlacementValue>1</>", LocalizedStrings=(("en","<PlacementNumberSymbol>#</><PlacementValue>1</>")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="BAFBD2E7447420DB97DD4EB958BE94DA", NativeString="<PlacementNumberSymbol>#</><PlacementValue>1</>", LocalizedStrings=(("en","<PlacementNumberSymbol>#</><PlacementValue>1</>")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="42B31291461096DFE0F34C99B5BD5A72", NativeString="<cap>V</>ICTORY", LocalizedStrings=(("en","<cap>V</>ICTORY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="4F7B9E6C47089B1CAADF259983B09563", NativeString="<cap>V</>ICTORY", LocalizedStrings=(("en","<cap>V</>ICTORY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="1622E7A444CF92D16B083E9DB17907C4", NativeString="<cap>R</>OYALE", LocalizedStrings=(("en","<cap>R</>OYALE")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="71DE29354A2AB0D1C24D85895B93023C", NativeString="<cap>R</>OYALE", LocalizedStrings=(("en","<cap>R</>OYALE")))
[AssetHotfix]